# Generated by Django 3.0.14 on 2021-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('transductors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='grouping',
            field=models.ManyToManyField(blank=True, help_text='This field is required', to='groups.Group', verbose_name='Grouping'),
        ),
    ]
